{% set name = "napari-deepmeta" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a98f4d4127f83a6a15accef6ca643b66dde8c37c92a75aabbb2b9028041837bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - connected-components-3d
    - napari ==0.4.8
    - napari-plugin-engine >=0.1.4
    - numpy
    - opencv
    - pyqt
    - pytest
    - pytest-cov
    - pytest-qt
    - pytest-xvfb
    - python >=3.6
    - qtpy >=1.9.0
    - scikit-image
    - tensorflow

test:
  imports:
    - deepmeta
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/EdgarLefevre/napari-deepmeta
  summary: Segment mouse lungs and metastasis on MRI images.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
